server {
    listen 8080;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # 支持 Angular 路由（刷新或直接访问非根路径时返回 index.html）
    location / {
        try_files $uri $uri/ /index.html;
    }

    # 可选：缓存静态资源
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    location /api/ {
        proxy_pass http://backend:8080/api/; #要用后端的docker的端口
        proxy_set_header Host $host;
    }
}