
#user  nobody;
worker_processes  3;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    # upstream 用于负载均衡
    upstream backendyio1{
        ip_hash;#设定同一个请求ip只访问8881/8882其中一个。默认是轮询。weight配置权重。所以结合起来就是只会访问8881
        server 127.0.0.1:8881 weight=3;
        server 127.0.0.1:8882;
    }
    upstream backendyio2{
        server 127.0.0.1:8882;
    }

    #重定向，http://localhost:80 会转跳到 https://localhost/
     server {
        listen       80;
        server_name  localhost;
        return 301 https://$server_name;
    }

    server {
        listen       443 ssl;
        # listen     8888; 自定义端口，使用http
        server_name  localhost;

        ssl_certificate /Users/a1-6/project/nginx/ssl/cacert.pem;
        ssl_certificate_key /Users/a1-6/project/nginx/ssl/private.key;
        ssl_session_timeout 5m;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        #access_log  logs/host.access.log  main;

        location /app1 {
            proxy_pass http://backendyio1;
        }
        location /app2 {
            proxy_pass http://backendyio2;
        }

        # Nginx 默认欢迎页：
        # 命令查看是哪个文件：brew info nginx | grep "Docroot"。
        # /opt/homebrew/var/www/index.html
        # 通过 https://localhost 访问
        location / {
            root   html;
            index  index.html index.htm;
        }

        #error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }

        # deny access to .htaccess files, if Apache's document root
        # concurs with nginx's one
        #
        #location ~ /\.ht {
        #    deny  all;
        #}
    }


    # another virtual host using mix of IP-, name-, and port-based configuration
    #
    #server {
    #    listen       8000;
    #    listen       somename:8080;
    #    server_name  somename  alias  another.alias;

    #    location / {
    #        root   html;
    #        index  index.html index.htm;
    #    }
    #}


    # HTTPS server
    #
    #server {
    #    listen       443 ssl;
    #    server_name  localhost;

    #    ssl_certificate      cert.pem;
    #    ssl_certificate_key  cert.key;

    #    ssl_session_cache    shared:SSL:1m;
    #    ssl_session_timeout  5m;

    #    ssl_ciphers  HIGH:!aNULL:!MD5;
    #    ssl_prefer_server_ciphers  on;

    #    location / {
    #        root   html;
    #        index  index.html index.htm;
    #    }
    #}
    include servers/*; # 会让nginx去读 基于本文件的位置下 servers/*里面的配置文件
}
