server.port=8080
# å³å®åç«¯çå®¹å¨ç«¯å£

# æå®æ¥å¿æä»¶è·¯å¾ãè¿éè®¾ä¸ºç¸å¯¹è·¯å¾ï¼æ¥å¿ä¼ç¸å¯¹äºè¿è¡ç®å½ï¼å³å®¹å¨åç /appï¼çæã
# å¦æä½¿ç¨ç»å¯¹è·¯å¾ï¼è¯·ç¡®ä¿ç®å½å­å¨ä¸æåå¥æéã
# ä¸ºä»ä¹æ¯ ./logsï¼å ä¸ºä½ ç Dockerfile ä¸­è®¾ç½®äº WORKDIR /appï¼æä»¥åºç¨è¿è¡å¨ /app ç®å½ä¸ãè®¾ç½®ç¸å¯¹è·¯å¾ ./logsï¼æ¥å¿å°±ä¼åå¥ /app/logs/ ç®å½ä¸­ã

# ZhiPuAI
# TODO: å¡«å¥ä½ èªå·±ç API Key
spring.ai.zhipuai.api-key=YOUR_ZHIPU_API_KEY
# å¦ææ¨¡ååææ´æ°ï¼ç´æ¥æ¹è¿éå³å¯ï¼ç¤ºä¾ï¼glm-4-flash-250414ï¼
spring.ai.zhipuai.chat.options.model=glm-4-flash
